export const AUTHSTATECHANGE = {
  PASSWORD_RECOVERY: "PASSWORD_RECOVERY",
  INITIAL_SESSION: "INITIAL_SESSION",
  SIGN_IN: "SIGN_IN",
  SIGN_OUT: "SIGN_OUT",
  TOKEN_REFRESHED: "TOKEN_REFRESHED",
  USER_UPDATED: "USER_UPDATED",
};
